# Generated by Django 6.0.2 on 2026-02-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newsletter",
            "0002_alter_message_created_at_alter_message_subscriber_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.RemoveField(
            model_name="message",
            name="subscriber",
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Тема письма"),
        ),
        migrations.AlterModelTable(
            name="message",
            table=None,
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Дата и время начала отправки"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("running", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="newsletter.subscriber", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
