# Generated by Django 6.0.2 on 2026-02-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_add_owner_and_is_disabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Менеджер: просмотр всех рассылок"),
                    ("can_disable_mailing", "Менеджер: отключение рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Менеджер: просмотр всех сообщений")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ["-created_at", "email"],
                "permissions": [
                    ("can_view_all_subscribers", "Менеджер: просмотр всех получателей")
                ],
                "verbose_name": "Подписчик",
                "verbose_name_plural": "Подписчики",
            },
        ),
    ]
