# Generated by Django 6.0.2 on 2026-02-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_messageattempt"),
    ]

    operations = []
